#!/usr/bin/env python3

import argparse
import gfdlvitals
import glob
import os
import shutil
import subprocess
import tempfile

def arguments():
    '''
    Function to capture the user-specified command line options
    '''
    description = '''
    Program for generating global mean statistics directly 
    from history tarfile.

    For help, contact John.Krasting@noaa.gov

    '''

    parser = argparse.ArgumentParser(description=description, 
                 formatter_class=argparse.RawTextHelpFormatter)

    parser.add_argument('historydir', metavar='HISTORY DIR', type=str,
        default=os.getcwd(), help='Path to /history directory')

    parser.add_argument('-o', '--outdir', type=str, default='./',
        help='Output directory. Default is current directory')

    parser.add_argument('-m', '--modelclass', type=str, default='generic',
        help='Model class. Options include generic, ESM2, ESM4, and OM4. Default is generic')

    parser.add_argument('-s', '--startyear', type=int, default=None,
        help='Starting year to process. Default is all years.')

    parser.add_argument('-e', '--endyear', type=int, default=None,
        help='Ending year to process. Default is all years.')

    parser.add_argument('-g', '--gridspec', type=str, default=None,
        help='Path to gridspec tarfile. Used in AMOC calculation. '+
             'Default is None')

    args = parser.parse_args()
    args.historydir = os.path.abspath(args.historydir)
    args.gridspec = os.path.abspath(args.gridspec)

    return args



def process_year(args,infile):
    #-- Set the model year string
    fYear = str(infile.split('/')[-1].split('.')[0])

    #-- Run the main code
    if args.modelclass == 'ESM2':
        gfdlvitals.models.ESM2.routines(args,infile)
    elif args.modelclass == 'ESM4':
        gfdlvitals.models.ESM4.routines(args,infile)
    elif args.modelclass == 'OM4':
        gfdlvitals.models.OM4.routines(args,infile)
    elif args.modelclass == 'generic':
        gfdlvitals.models.generic.routines(args,infile)

    #-- Move results to their final location 
    if not os.path.exists(args.outdir):
      os.makedirs(args.outdir)
    for reg in ['global','nh','sh','tropics']:
      for component in ['Land','Atmos','Ocean','Ice','TOPAZ','BLING','Timing']:
        if os.path.exists(fYear+'.'+reg+'Ave'+component+'.db'):
          if not os.path.exists(args.outdir+'/'+reg+'Ave'+component+'.db'):
            shutil.copyfile(fYear+'.'+reg+'Ave'+component+'.db',args.outdir+\
                '/'+reg+'Ave'+component+'.db')
          else:
            gfdlvitals.util.merge.merge(fYear+'.'+reg+'Ave'+component+'.db',
                args.outdir+'/'+reg+'Ave'+component+'.db')



if __name__ == '__main__':
    args = arguments()

    #-- Obtain git commit hash for provenance
    script_dir = os.path.dirname(os.path.abspath(__file__))
    commit = gfdlvitals.util.git.retrieve_commit(script_dir)
    clean = gfdlvitals.util.git.is_clean(script_dir)
    if clean is True:
        args.commit = commit
    else:
        args.commit = None
    print('Using gfdlvitals version '+gfdlvitals.__version__+
          ' -- git version ' +str(args.commit))

    args.outdir = os.path.abspath(args.outdir)

    #-- Get a list of history files
    dirlist = sorted(glob.glob(args.historydir+"/*.tar"))

    #-- Apply start and end year limits, if applicable
    infiles = []
    if (args.startyear is not None) or (args.endyear is not None):
        if args.startyear is None:
            args.startyear = -1
        if args.endyear is None:
            args.endyear = 99999
        for f in dirlist:
            yr = int(os.path.basename(f)[0:4])
            if (yr >= args.startyear) and (yr <= args.endyear):
                infiles.append(f)
    else:
        infiles = dirlist

    #-- DMGET the history files
    if shutil.which('dmget') is not None:
        print('Dmgetting files ...')
        subprocess.call(['dmget']+infiles)
        print('Complete!')

    #-- Make temporary directory to work in 
    cwd = os.getcwd()
    tempdir = tempfile.mkdtemp()
    os.chdir(tempdir)

    #-- Loop over history files
    for infile in infiles:
        process_year(args,infile)
    
    #-- Clean up 
    os.chdir(cwd)
    shutil.rmtree(tempdir)

    exit()
